### PR TITLE
Configurable logging levels in `VSphereSource`

### LINKED ISSUE #343: [BUG] Adapter doesn't support configuring log levels
**Describe the bug**
If you configure the `config-logging` CM you should see your adapters restart with the same log level. https://github.com/vmware-tanzu/sources-for-knative/blob/main/pkg/reconciler/vspheresource/resources/deployment.go#L90-L91 implies that they never log at anything but the default (INFO)

### PR DESCRIPTION
**Pull request by embano1**
Fixes #343

## Proposed Changes

- :bug: Logging and metrics can be changed at runtime for all vSphere components
- :broom: Enhance logging in certain vSphere adapter areas
- Describe how to change logging in README

Note: The implementation follows the dynamic logging/metrics configuration pattern used in [`rabbitmqsource`](https://github.com/knative-sandbox/eventing-rabbitmq/blob/07661b9d44f5933d0949f9a23781c84e8a2fc55b/pkg/reconciler/source/rabbitmqsource.go#L189)

### Pre-review Checklist

- [x] **At least 80% unit test coverage**
- [ ] **E2E tests** for any new behavior
- [x] **Docs** for any user-facing impact

**Release Note**

```release-note
The logging level for the `VSphereSource` and `VSphereBinding` components, i.e. `vsphere-source-webhook` and `adapter` `Deployments`, can now be changed at runtime.
```

### CODE REVIEW

**Comment by embano1** [comment]
cc-ing FYI @KauzClay

File: pkg/vsphere/adapter.go [hunk 1]
```diff
@@ -178,8 +177,14 @@ func (a *vAdapter) readEvents(ctx context.Context, c *event.HistoryCollector) er
 			// avoid unnecessary K8s API calls
 			skip := lastEvent == nil || lastCheckpointEventKey == lastEvent.GetEvent().Key
 			if !skip {
-				logger.Debug("creating checkpoint")
-				if err := a.KVStore.Save(ctx); err != nil {
+				var current checkpoint
+				err := a.KVStore.Get(ctx, checkpointKey, &current)
```
Comment (gabo1208) [inline pkg/vsphere/adapter.go:181]: this could also be in the same line as the if
`if err := a.KVStore.Get(ctx, checkpointKey, &current); err != nil ...`

File: README.md [hunk 2]
```diff
@@ -369,3 +369,148 @@ This has been tested with:
...
+kubectl get vspheresource
+NAME                SOURCE                     SINK                                                                              READY   REASON
+example-vc-source   https://my-vc.corp.local   http://broker-ingress.knative-eventing.svc.cluster.local/default/example-broker   True
+
+kubectl scale deployment --replicas 0 example-vc-source-deployment
+deployment.apps/example-vc-source-deployment scaled
+```
+
+⚠️ **Note:** To avoid losing events due to this (brief) downtime, use the
+[Checkpointing](#configuring-checkpoint-and-event-replay) capability.
```
Comment (evankanderson) [inline README.md:465]: Should we be enabling this by default so that we can roll out the deployment automatically on these changes?

**Review by evankanderson — DISMISSED** [review]
+1 to adding the actual event info as debug logs.

File: README.md (hunk 2 above)
Comment (embano1) [reply README.md:465]: When we introduced this in an earlier version, we did not want to break users and hence the default is no checkpointing. I agree with you thought, that we should provide safe defaults. Let me create an issue to enable checkpointing by default.

Comment (embano1) [reply README.md:465]: https://github.com/vmware-tanzu/sources-for-knative/issues/403

File: README.md [hunk 3]
```diff
@@ -369,3 +369,148 @@ This has been tested with:
...
+`Source` controller will react to this change by creating a new instance (`Pod`)
+with the desired log level changes and setting `replicas` to the default count
+(`1`) again.
+
+```
+kubectl get vspheresource
+NAME                SOURCE                     SINK                                                                              READY   REASON
+example-vc-source   https://my-vc.corp.local   http://broker-ingress.knative-eventing.svc.cluster.local/default/example-broker   True
+
+kubectl scale deployment --replicas 0 example-vc-source-deployment
```
[the remark this answers is not in the document]
Comment (embano1) [reply README.md:460]: > `kubectl rollout restart deployment/example-vc-source-deployment` might be another usable command here.

You are a genius! Why did I not think of `rollout` 🤦 ?!?
 
> I'm assuming this is a point-in time thing, or do we expect end-users to do this as needed when they change the logging level?

I had some discussions on how this is handled in general in the Knative space. Currently it seems that there's no consensus on whether/how to automatically propagate these changes to child objects, e.g. `adapters`  managed by `controllers.`

This is especially a concern when the user needs control over the sequence/lifecycle of `adapters`, e.g. to avoid redelivery of events, etc.

In our case, we have at-most-once and at-least-once (w/ checkpointing enabled) behavior, i.e. once the user manually updates the `adapter` as per her/his defined operation window ("downtime"), we are still guaranteeing this but leaving the control over the downtime in the hand of the operator (manual).

Every time an operator decides to change the log level (which I suspect is not going to happen a lot, e.g. only when needing to `debug`), this `kubectl ...` dance is required.

**Review by gabo1208 — APPROVED** [review]
